CREATE TABLE goal
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    deadline     TIMESTAMP WITHOUT TIME ZONE,
    start_date   TIMESTAMP WITHOUT TIME ZONE,
    is_complete  BOOLEAN,
    is_long_term BOOLEAN,
    notes        VARCHAR(255),
    CONSTRAINT pk_goal PRIMARY KEY (id)
);